### ISSUE TITLE
Checkpoint 1

### ISSUE THREAD

**Issue by MNuenninghoff** [MNuenninghoff/NPCCreator#1]
@pawaitemadisoncollege  checkpoint 1 ready for review

**Comment by pawaitemadisoncollege** [comment]
Thanks for sharing your indie project checkpoint 1 @MNuenninghoff! You are off to a very solid start (I see some code already!) and have such a fun and useful project to work on. Solving a problem _you_ have can help keep you motivated. 

Following are my observations and suggestions:

**Problem statement**

Does a good job clearly laying out the problem and explaining how your application solves it.

- [x] This might be a little nitpicky, but this wording felt off to me: "Need a barkeeper who has _something_ a unique trait? "

**User stories**

Your MVP user stories feel like they are right-sized for the semester and are clearly stated.

- [ ] Is there a meaningful delete story that you could include (I noticed a delete button in the screens)?
- [ ] Should have a sign out user story too.
- [ ] This wouldn't necessarily be a specific user story, but I don't want to lose track of the requirement for a web service.
- [ ] Should there be a search story? How will users locate an NPC to view?

**Project plan**

Looks sort of familiar! 

- [x] Remember to check things off as you complete them.
- [ ] Keep modifying the plan (adding tasks) as you learn more!  What's not covered yet?

**Screen design**

Love the hand-drawn screens. 

- [ ] Curious how a user finds the previously saved NPCs? Should there be a screen for this? Maybe the question is, is there a View NPC screen not shown? 

**Reflection statements/Time Log**

Great work consistently tracking!
